# See: https://github.com/licensee/licensed/blob/main/docs/configuration.md

sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - other
  - 0bsd
  - blueoak-1.0.0

ignored:
  npm:
    # Used by Rollup.js when building in GitHub Actions
    - '@rollup/rollup-linux-x64-gnu'
    - '@bufbuild/protobuf'
    - 'buffers'
    - 'chainsaw'
